DROP TABLE PACZKA;
DROP TABLE NADAWCA;
DROP TABLE ODBIORCA;
DROP TABLE KLIENT;
DROP TABLE KURIER;
DROP TABLE DZIELNICA;
DROP TABLE REJON;
DROP TABLE MIASTO;
DROP TABLE DYSPOZYTOR;
DROP TABLE PUNKTSTACJONARNY;
DROP TABLE SAMOCHOD;
DROP TABLE PRACOWNIK;

CREATE TABLE PRACOWNIK (
    IDPRACOWNIK NUMBER(*, 0) NOT NULL,
    IMIE VARCHAR2(32) NOT NULL,
    NAZWISKO VARCHAR2(64) NOT NULL,
    DATAZATRUDNIENIA DATE,
    CONSTRAINT PRACOWNIK_PK PRIMARY KEY  (IDPRACOWNIK)
);

CREATE TABLE DYSPOZYTOR (
    IDDYSPOZYTOR NUMBER(*, 0) NOT NULL,
    IDPUNKT NUMBER(*, 0) NOT NULL,
    CONSTRAINT DYSPOZYTOR_PK PRIMARY KEY  (IDDYSPOZYTOR)
);

CREATE TABLE KURIER (
    IDKURIER NUMBER(*, 0) NOT NULL,
    IDSAMOCHOD CHAR(10) NOT NULL,
    NRTELEFONU NUMBER(9,0),
    IDDYSPOZYTOR NUMBER(*, 0),
    IDREJON NUMBER(*, 0),
    CONSTRAINT KURIER_PK PRIMARY KEY (IDKURIER)
);

CREATE TABLE SAMOCHOD (
    NRREJESTRACYJNY CHAR(10) NOT NULL,
    MARKA VARCHAR2(32),
    ROKPRODUKCJI DATE,
    PRZEBIEG NUMBER(*, 0),
    RODZAJPALIWA VARCHAR2(32),
    CONSTRAINT SAMOCHOD_PK PRIMARY KEY (NRREJESTRACYJNY)
);

CREATE TABLE MIASTO (
    IDMIASTO NUMBER(*, 0) NOT NULL,
    NAZWA VARCHAR2(32) NOT NULL,
    CONSTRAINT MIASTO_PK PRIMARY KEY (IDMIASTO)
);

CREATE TABLE REJON (
    IDREJON NUMBER(*, 0) NOT NULL,
    IDMIASTO NUMBER(*, 0) NOT NULL,
    CONSTRAINT REJON_PK PRIMARY KEY (IDREJON)
);

CREATE TABLE DZIELNICA (
    IDDZIELNICA NUMBER(*, 0) NOT NULL,
    NAZWA VARCHAR2(32) NOT NULL,
    IDREJON NUMBER(*, 0) NOT NULL,
    IDMIASTO NUMBER(*, 0) NOT NULL,
    CONSTRAINT DZIELNICA_PK PRIMARY KEY (IDDZIELNICA)
);

CREATE TABLE PUNKTSTACJONARNY (
    IDPUNKT NUMBER(*, 0) NOT NULL,
    IDDZIELNICA NUMBER(*, 0) NOT NULL,
    CONSTRAINT PUNKT_PK PRIMARY KEY (IDPUNKT)
);

CREATE TABLE PACZKA (
    IDPACZKA NUMBER(*, 0) NOT NULL,
    IDKURIER NUMBER(*, 0),
    IDNADAWCA NUMBER(*, 0) NOT NULL,
    IDODBIORCA NUMBER(*, 0) NOT NULL,
    IDPUNKT NUMBER(*, 0),
    WARTOSC NUMBER(*, 0),
    WAGA NUMBER(*, 2),
    DATANADANIA DATE,
    CONSTRAINT PACZKA_PK PRIMARY KEY (IDPACZKA)
);

CREATE TABLE KLIENT (
    IDKLIENT NUMBER(*, 0) NOT NULL,
    IMIE VARCHAR2(32) NOT NULL,
    NAZWISKO VARCHAR2(64) NOT NULL,
    NRTELEFONU CHAR(9) NOT NULL,
    CONSTRAINT KLIENT_PK PRIMARY KEY (IDKLIENT)
);

CREATE TABLE NADAWCA (
    IDNADAWCA NUMBER(*, 0) NOT NULL,
    RABAT NUMBER(38,2),
    ILOSCPACZEK NUMBER (*, 0),
    CONSTRAINT NADAWCA_PK PRIMARY KEY (IDNADAWCA)
);

CREATE TABLE ODBIORCA (
    IDODBIORCA NUMBER(*, 0) NOT NULL,
    IDMIASTO NUMBER(*, 0),
    ADRES VARCHAR2(64),
    CONSTRAINT ODBIORCA_PK PRIMARY KEY (IDODBIORCA)
);

ALTER TABLE NADAWCA ADD CONSTRAINT NADAWCA_KLIENT_FK1 FOREIGN KEY(IDNADAWCA) REFERENCES KLIENT(IDKLIENT);
ALTER TABLE ODBIORCA ADD CONSTRAINT ODBIORCA_KLIENT_FK1 FOREIGN KEY(IDODBIORCA) REFERENCES KLIENT(IDKLIENT);
ALTER TABLE ODBIORCA ADD CONSTRAINT ODBIORCA_MIASTO_FK1 FOREIGN KEY(IDMIASTO) REFERENCES MIASTO(IDMIASTO);

ALTER TABLE PACZKA ADD CONSTRAINT PACZKA_KURIER_FK1 FOREIGN KEY(IDKURIER) REFERENCES KURIER(IDKURIER);
ALTER TABLE PACZKA ADD CONSTRAINT PACZKA_NADAWCA_FK1 FOREIGN KEY(IDNADAWCA) REFERENCES KLIENT(IDKLIENT);
ALTER TABLE PACZKA ADD CONSTRAINT PACZKA_ODBIORCA_FK1 FOREIGN KEY(IDODBIORCA) REFERENCES KLIENT(IDKLIENT);
ALTER TABLE PACZKA ADD CONSTRAINT PACZKA_PUNKT_FK1 FOREIGN KEY(IDPUNKT) REFERENCES PUNKTSTACJONARNY(IDPUNKT);

ALTER TABLE DYSPOZYTOR ADD CONSTRAINT PRACOWNIK_DYSPOZYTOR_FK1 FOREIGN KEY(IDDYSPOZYTOR) REFERENCES PRACOWNIK(IDPRACOWNIK);
ALTER TABLE DYSPOZYTOR ADD CONSTRAINT PUNKT_DYSPOZYTOR_FK1 FOREIGN KEY(IDPUNKT) REFERENCES PUNKTSTACJONARNY(IDPUNKT);

ALTER TABLE KURIER ADD CONSTRAINT PRACOWNIK_KURIER_FK1 FOREIGN KEY(IDKURIER) REFERENCES PRACOWNIK(IDPRACOWNIK);
ALTER TABLE KURIER ADD CONSTRAINT DYSPOZYTOR_KURIER_FK1 FOREIGN KEY(IDDYSPOZYTOR) REFERENCES DYSPOZYTOR(IDDYSPOZYTOR);
ALTER TABLE KURIER ADD CONSTRAINT SAMOCHOD_KURIER_FK1 FOREIGN KEY(IDSAMOCHOD) REFERENCES SAMOCHOD(NRREJESTRACYJNY);
ALTER TABLE KURIER ADD CONSTRAINT REJON_KURIER_FK1 FOREIGN KEY(IDREJON) REFERENCES REJON(IDREJON);

ALTER TABLE DZIELNICA ADD CONSTRAINT DZIELNICA_REJON_FK1 FOREIGN KEY(IDREJON) REFERENCES REJON(IDREJON);
ALTER TABLE DZIELNICA ADD CONSTRAINT DZIELNICA_MIASTO_FK1 FOREIGN KEY(IDMIASTO) REFERENCES MIASTO(IDMIASTO);

ALTER TABLE REJON ADD CONSTRAINT REJON_MIASTO_FK1 FOREIGN KEY(IDMIASTO) REFERENCES MIASTO(IDMIASTO);


INSERT ALL
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (1, 'ZENON', 'XENON', '2010-12-01')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (2, 'HARRY', 'POTTER', '2011-03-02')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (3, 'RON', 'WEASLEY', '2012-02-03')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (4, 'PETER', 'PETTIGREW', '2013-11-04')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (5, 'HAGRID', 'HAGRID', '2014-10-01')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (6, 'LORD', 'VOLDEMORT', '2014-02-02')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (7, 'HORACY', 'SLUGHORN', '2014-04-27')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (8, 'SEVERUS', 'SNAPE', '2012-05-11')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (9, 'DOLORES', 'XUMBRIDGE', '2013-04-01')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (10, 'SYRIUS', 'BLACK', '2015-02-13')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (11, 'SYRIUS', 'WHITE', '2015-07-25')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (12, 'SYRIUS', 'GREEN', '2015-11-11')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (13, 'DRACO', 'MALFOY', '2016-01-19')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (14, 'DUDLEY', 'DURSLEY', '2011-05-01')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (15, 'PETUNIA', 'DURSLEY', '2009-08-08')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (16, 'MUNGUS', 'FLETCHER', '2009-01-01')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (17, 'ALBUS', 'DUMBLEDORE', '2011-10-22')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (18, 'NEARLY HEADLESS', 'NICK', '2012-12-23')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (19, 'BLOODY', 'BARON', '2017-01-31')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (20, 'FAT', 'LADY', '2016-11-15')
INTO PRACOWNIK (IDPRACOWNIK, IMIE, NAZWISKO, DATAZATRUDNIENIA) VALUES (21, 'MISS', 'NORISS', '2010-03-14')
SELECT * FROM DUAL; 

INSERT ALL
INTO MIASTO (IDMIASTO, NAZWA) VALUES (1, 'WARSZAWA')
INTO MIASTO (IDMIASTO, NAZWA) VALUES (2, 'WROCLAW')
INTO MIASTO (IDMIASTO, NAZWA) VALUES (3 ,'KRAKOW')
INTO MIASTO (IDMIASTO, NAZWA) VALUES (4, 'RADOM')
INTO MIASTO (IDMIASTO, NAZWA) VALUES (5, 'OTWOCK')
SELECT * FROM DUAL;

INSERT ALL
INTO REJON (IDREJON, IDMIASTO) VALUES (1, 1)
INTO REJON (IDREJON, IDMIASTO) VALUES (2, 1)
INTO REJON (IDREJON, IDMIASTO) VALUES (3, 1)
INTO REJON (IDREJON, IDMIASTO) VALUES (4, 1)
INTO REJON (IDREJON, IDMIASTO) VALUES (5, 1)
INTO REJON (IDREJON, IDMIASTO) VALUES (6, 2)
INTO REJON (IDREJON, IDMIASTO) VALUES (7, 2)
INTO REJON (IDREJON, IDMIASTO) VALUES (8, 2)
INTO REJON (IDREJON, IDMIASTO) VALUES (9, 3)
INTO REJON (IDREJON, IDMIASTO) VALUES (10,4)
INTO REJON (IDREJON, IDMIASTO) VALUES (11, 4)
INTO REJON (IDREJON, IDMIASTO) VALUES (12,5)
SELECT * FROM DUAL;

INSERT ALL
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (1, 'OCHOTA', 1, 1)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (2, 'MOKOTOW', 1, 1)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (3, 'BEMOWO', 1, 1)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (4, 'SRODMIESCIE', 2, 1)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (5, 'URSYNOW', 2, 1)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (6, 'BIELANY', 3, 1)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (7, 'PRAGA', 3, 1)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (8, 'TARGOWEK', 4, 1)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (9, 'WOLA', 5, 1)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (10, 'KRZYKI', 6, 2)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (11, 'KOZANOW', 6, 2)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (12, 'CENTRUM', 7, 2)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (13, 'ZAPOROZE', 7, 2)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (14, 'WLOCHY', 8, 2)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (15, 'WAWEL', 9, 3)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (16, 'LAZIENKI', 9, 3)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (17, 'RESZTAKRAKOWA', 9, 3)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (18, 'PORTLOTNICZY', 10, 4)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (19, 'DROGAWYJAZDOWA', 11, 4)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (20, 'OTWOCK MALY', 12, 5)
INTO DZIELNICA (IDDZIELNICA, NAZWA, IDREJON, IDMIASTO) VALUES (21, 'OTWOCK WIEKSZY', 12, 5)
SELECT * FROM DUAL;

INSERT ALL
INTO PUNKTSTACJONARNY (IDPUNKT, IDDZIELNICA) VALUES (2, 1)
INTO PUNKTSTACJONARNY (IDPUNKT, IDDZIELNICA) VALUES (3, 1)
INTO PUNKTSTACJONARNY (IDPUNKT, IDDZIELNICA) VALUES (6, 3)
INTO PUNKTSTACJONARNY (IDPUNKT, IDDZIELNICA) VALUES (9, 4)
INTO PUNKTSTACJONARNY (IDPUNKT, IDDZIELNICA) VALUES (10, 5)
INTO PUNKTSTACJONARNY (IDPUNKT, IDDZIELNICA) VALUES (12, 6)
SELECT * FROM DUAL;

INSERT ALL
INTO DYSPOZYTOR (IDDYSPOZYTOR, IDPUNKT) VALUES (1, 2)
INTO DYSPOZYTOR (IDDYSPOZYTOR, IDPUNKT) VALUES (3, 2)
INTO DYSPOZYTOR (IDDYSPOZYTOR, IDPUNKT) VALUES (5, 3)
INTO DYSPOZYTOR (IDDYSPOZYTOR, IDPUNKT) VALUES (7, 6)
INTO DYSPOZYTOR (IDDYSPOZYTOR, IDPUNKT) VALUES (9, 9)
INTO DYSPOZYTOR (IDDYSPOZYTOR, IDPUNKT) VALUES (11, 10)
INTO DYSPOZYTOR (IDDYSPOZYTOR, IDPUNKT) VALUES (13, 12)
INTO DYSPOZYTOR (IDDYSPOZYTOR, IDPUNKT) VALUES (15, 12)
SELECT * FROM DUAL;

INSERT ALL 
INTO SAMOCHOD(NRREJESTRACYJNY, MARKA, ROKPRODUKCJI, PRZEBIEG, RODZAJPALIWA) VALUES ('WWW 0001', 'FIAT' , TO_DATE('1990', 'YYYY'), 353353, 'BENZYNA')
INTO SAMOCHOD(NRREJESTRACYJNY, MARKA, ROKPRODUKCJI, PRZEBIEG, RODZAJPALIWA) VALUES ('WWW 0002', 'FIAT' , TO_DATE('1991', 'YYYY'), 111111, 'BENZYNA')
INTO SAMOCHOD(NRREJESTRACYJNY, MARKA, ROKPRODUKCJI, PRZEBIEG, RODZAJPALIWA) VALUES ('WWW 0003', 'POLONEZ' , TO_DATE('1992', 'YYYY'), 323123, 'BENZYNA')
INTO SAMOCHOD(NRREJESTRACYJNY, MARKA, ROKPRODUKCJI, PRZEBIEG, RODZAJPALIWA) VALUES ('WWW 0004', 'POLONEZ' , TO_DATE('1993', 'YYYY'), 23871, 'GAZ')
INTO SAMOCHOD(NRREJESTRACYJNY, MARKA, ROKPRODUKCJI, PRZEBIEG, RODZAJPALIWA) VALUES ('WWW 0005', 'SKODA' , TO_DATE('1994', 'YYYY'), 743894, 'BENZYNA')
INTO SAMOCHOD(NRREJESTRACYJNY, MARKA, ROKPRODUKCJI, PRZEBIEG, RODZAJPALIWA) VALUES ('WWW 0006', 'SKODA' , TO_DATE('1991', 'YYYY'), 12000, 'GAZ')
INTO SAMOCHOD(NRREJESTRACYJNY, MARKA, ROKPRODUKCJI, PRZEBIEG, RODZAJPALIWA) VALUES ('WWW 0007', 'SKODA' , TO_DATE('1993', 'YYYY'), 999890, 'BENZYNA')
INTO SAMOCHOD(NRREJESTRACYJNY, MARKA, ROKPRODUKCJI, PRZEBIEG, RODZAJPALIWA) VALUES ('WWW 0008', 'TRABANT' , TO_DATE('2011', 'YYYY'), 56789, 'DIESEL')
INTO SAMOCHOD(NRREJESTRACYJNY, MARKA, ROKPRODUKCJI, PRZEBIEG, RODZAJPALIWA) VALUES ('WWW 0009', 'SYRENKA' , TO_DATE('2017', 'YYYY'), 100, 'PRAD')
INTO SAMOCHOD(NRREJESTRACYJNY, MARKA, ROKPRODUKCJI, PRZEBIEG, RODZAJPALIWA) VALUES ('WWW 0010', 'FIAT' , TO_DATE('1990', 'YYYY'), 120120, 'DIESEL')
SELECT * FROM DUAL;

INSERT ALL
INTO KURIER(IDKURIER, IDSAMOCHOD, NRTELEFONU, IDDYSPOZYTOR, IDREJON) VALUES(2, 'WWW 0001', 999999999, 1, 1)
INTO KURIER(IDKURIER, IDSAMOCHOD, NRTELEFONU, IDDYSPOZYTOR, IDREJON) VALUES(4, 'WWW 0002', 999999998, 3, 2)
INTO KURIER(IDKURIER, IDSAMOCHOD, NRTELEFONU, IDDYSPOZYTOR, IDREJON) VALUES(6, 'WWW 0002', 999999997, 3, 2)
INTO KURIER(IDKURIER, IDSAMOCHOD, NRTELEFONU, IDDYSPOZYTOR, IDREJON) VALUES(8, 'WWW 0003', 999999996, 1, 1)
INTO KURIER(IDKURIER, IDSAMOCHOD, NRTELEFONU, IDDYSPOZYTOR, IDREJON) VALUES(10, 'WWW 0004', 999999995, 5, 3)
INTO KURIER(IDKURIER, IDSAMOCHOD, NRTELEFONU, IDDYSPOZYTOR, IDREJON) VALUES(12, 'WWW 0005', 999999994, 5, 3)
INTO KURIER(IDKURIER, IDSAMOCHOD, NRTELEFONU, IDDYSPOZYTOR, IDREJON) VALUES(14, 'WWW 0006', 999999993, 7, 4)
INTO KURIER(IDKURIER, IDSAMOCHOD, NRTELEFONU, IDDYSPOZYTOR, IDREJON) VALUES(16, 'WWW 0007', 999999992, 9, 5)
INTO KURIER(IDKURIER, IDSAMOCHOD, NRTELEFONU, IDDYSPOZYTOR, IDREJON) VALUES(17, 'WWW 0007', 999999991, 9, 5)
INTO KURIER(IDKURIER, IDSAMOCHOD, NRTELEFONU, IDDYSPOZYTOR, IDREJON) VALUES(18, 'WWW 0008', 999999990, 11, 6)
INTO KURIER(IDKURIER, IDSAMOCHOD, NRTELEFONU, IDDYSPOZYTOR, IDREJON) VALUES(19, 'WWW 0009', 999999989, 15, 7)
INTO KURIER(IDKURIER, IDSAMOCHOD, NRTELEFONU, IDDYSPOZYTOR, IDREJON) VALUES(20, 'WWW 0010', 999999988, 13, 8)
INTO KURIER(IDKURIER, IDSAMOCHOD, NRTELEFONU, IDDYSPOZYTOR, IDREJON) VALUES(21, 'WWW 0010', 999999987, 13, 8)
SELECT * FROM DUAL;

INSERT ALL
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (1, 'ZENON', 'XENON', 111111112)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (2, 'HARRY', 'POTTER', 111111113)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (3, 'RON', 'WEASLEY', 111111111)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (4, 'PETER', 'PETTIGREW', 111111114)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (5, 'HAGRID', 'HAGRID', 111111116)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (6, 'LORD', 'VOLDEMORT', 111111117)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (7, 'HORACY', 'SLUGHORN', 111111118)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (8, 'SEVERUS', 'SNAPE', 111111119)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (9, 'DOLORES', 'XUMBRIDGE', 111111110)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (10, 'SYRIUS', 'BLACK', 111111121)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (11, 'SYRIUS', 'WHITE', 111111122)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (12, 'SYRIUS', 'GREEN', 111111123)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (13, 'DRACO', 'MALFOY', 111111124)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (14, 'DUDLEY', 'DURSLEY', 111111125)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (15, 'PETUNIA', 'DURSLEY', 111111126)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (16, 'MUNGUS', 'FLETCHER', 111111127)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (17, 'ALBUS', 'DUMBLEDORE', 111111128)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (18, 'NEARLY HEADLESS', 'NICK', 111111129)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (19, 'BLOODY', 'BARON', 111111130)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (20, 'FAT', 'LADY', 111111131)
INTO KLIENT (IDKLIENT, IMIE, NAZWISKO, NRTELEFONU) VALUES (21, 'MISS', 'NORISS', 111111132)
SELECT * FROM DUAL;

INSERT ALL
INTO NADAWCA (IDNADAWCA, RABAT, ILOSCPACZEK) VALUES(1, 0.1, 1)
INTO NADAWCA (IDNADAWCA, RABAT, ILOSCPACZEK) VALUES(3, 0.1, 1)
INTO NADAWCA (IDNADAWCA, RABAT, ILOSCPACZEK) VALUES(5, 0.3, 3)
INTO NADAWCA (IDNADAWCA, RABAT, ILOSCPACZEK) VALUES(7, 0.1, 1)
INTO NADAWCA (IDNADAWCA, RABAT, ILOSCPACZEK) VALUES(9, 0.1, 1)
INTO NADAWCA (IDNADAWCA, RABAT, ILOSCPACZEK) VALUES(11, 0.1, 1)
INTO NADAWCA (IDNADAWCA, RABAT, ILOSCPACZEK) VALUES(13, 0.4, 4)
INTO NADAWCA (IDNADAWCA, RABAT, ILOSCPACZEK) VALUES(15, 0.1, 1)
INTO NADAWCA (IDNADAWCA, RABAT, ILOSCPACZEK) VALUES(17, 0.5, 5)
INTO NADAWCA (IDNADAWCA, RABAT, ILOSCPACZEK) VALUES(19, 0.1, 1)
INTO NADAWCA (IDNADAWCA, RABAT, ILOSCPACZEK) VALUES(21, 0.9, 4)
SELECT * FROM DUAL;

INSERT ALL 
INTO ODBIORCA (IDODBIORCA, IDMIASTO, ADRES) VALUES (2, 2, 'GRANICZNA 4/2')
INTO ODBIORCA (IDODBIORCA, IDMIASTO, ADRES) VALUES (4, 2, 'GRANICZNA 5/2')
INTO ODBIORCA (IDODBIORCA, IDMIASTO, ADRES) VALUES (6, 2, 'GRANICZNA 6/2')
INTO ODBIORCA (IDODBIORCA, IDMIASTO, ADRES) VALUES (8, 4, 'SLONECZNA 19A')
INTO ODBIORCA (IDODBIORCA, IDMIASTO, ADRES) VALUES (10, 5, 'MIMOZOWA 13')
INTO ODBIORCA (IDODBIORCA, IDMIASTO, ADRES) VALUES (12, 1, 'NALESNIKOWA 1')
INTO ODBIORCA (IDODBIORCA, IDMIASTO, ADRES) VALUES (14, 2, 'BALONOWA 4/2')
INTO ODBIORCA (IDODBIORCA, IDMIASTO, ADRES) VALUES (16, 3, 'NIEBIESKA 3')
INTO ODBIORCA (IDODBIORCA, IDMIASTO, ADRES) VALUES (18, 5, 'ZIELONA 2')
INTO ODBIORCA (IDODBIORCA, IDMIASTO, ADRES) VALUES (20, 5, 'BRZOZOWA 1')
INTO ODBIORCA (IDODBIORCA, IDMIASTO, ADRES) VALUES (1, 4, 'CZERWONA 11')
SELECT * FROM DUAL;

INSERT ALL 
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA, WARTOSC, WAGA, DATANADANIA) VALUES (1, 2, 1, 4, 750, 10, TO_DATE('2017-04-10','YY-MM-DD'))
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA, DATANADANIA) VALUES (2, 2, 3, 4, TO_DATE('2017-05-09','YY-MM-DD'))
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA) VALUES (3, 4, 5, 2)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA) VALUES (4, 4, 5, 6)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA) VALUES (5, 4, 5, 6)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA) VALUES (6, 8, 9, 8)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA, WARTOSC, WAGA) VALUES (7, 10, 7, 10, 120, 5)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA, WARTOSC, WAGA) VALUES (8, 12, 11, 10, 100, 5)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA, WARTOSC, WAGA) VALUES (9, 12, 17, 12, 100, 2)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA, WARTOSC, WAGA) VALUES (10, 12, 17, 12, 80, 3)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA, WARTOSC, WAGA) VALUES (11, 14, 17, 12, 220, 1)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA, WAGA) VALUES (12, 14, 17, 12, 5)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA, WAGA) VALUES (13, 14, 17, 14, 10)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA, WAGA) VALUES (14, 16, 21, 14, 12)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA, WAGA) VALUES (15, 17, 21, 14, 1)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA, WAGA) VALUES (16, 17, 21, 16, 1)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA, WAGA) VALUES (17, 18, 21, 16, 1)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA) VALUES (18, 19, 19, 18)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA) VALUES (19, 20, 15, 20)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA) VALUES (20, 21, 13, 20)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA) VALUES (21, 21, 13, 20)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA) VALUES (22, 21, 13, 20)
INTO PACZKA (IDPACZKA, IDKURIER, IDNADAWCA, IDODBIORCA) VALUES (23, 21, 13, 1)
SELECT * FROM DUAL;