CREATE TRIGGER PRZYZNAJRABAT
ON PACZKA 
FOR INSERT
AS
BEGIN 
DECLARE CUR CURSOR FOR SELECT IDNADAWCA FROM INSERTED
DECLARE @ID INT, @IMIE VARCHAR(50), @NAZWISKO VARCHAR(50), @RABAT DECIMAL(2,1);
OPEN CUR
FETCH NEXT FROM CUR INTO @ID
WHILE @@FETCH_STATUS = 0
    BEGIN
        IF (SELECT 1 FROM NADAWCA WHERE IDNADAWCA = @ID) IS NOT NULL
            BEGIN
                UPDATE NADAWCA SET RABAT = RABAT + 0.1 WHERE IDNADAWCA = @ID
                UPDATE NADAWCA SET ILOSCPACZEK = ILOSCPACZEK + 1 WHERE IDNADAWCA = @ID
                SELECT @IMIE = IMIE, @NAZWISKO = NAZWISKO, @RABAT = RABAT FROM KLIENT JOIN NADAWCA ON NADAWCA.IDNADAWCA = KLIENT.IDKLIENT WHERE IDKLIENT = @ID
                SELECT 'PRZYZNANO RABAT DLA: ' + @IMIE +  ' ' + @NAZWISKO + ', W WYSOKOSCI: ' + CAST(@RABAT AS VARCHAR);
            END
        ELSE
            BEGIN                
                INSERT INTO NADAWCA (IDNADAWCA, RABAT, ILOSCPACZEK) VALUES (@ID, 0.1, 1);
                SELECT @IMIE = IMIE, @NAZWISKO = NAZWISKO, @RABAT = RABAT FROM KLIENT JOIN NADAWCA ON NADAWCA.IDNADAWCA = KLIENT.IDKLIENT WHERE IDKLIENT = @ID
                SELECT 'DODANO NOWEGO NADAWCE: ' + @IMIE +  ' ' + @NAZWISKO + ', RABAT NA POCZATEK: ' + CAST(@RABAT AS VARCHAR);
            END
        FETCH NEXT FROM CUR INTO @ID
    END
END

GO